export interface Property {
  id: number
  title: string
  location: string
  city: 'Bangalore' | 'London'
  price: number
  currency: '₹' | '£'
  rating: number
  verified: boolean
  type: 'PG' | 'Hostel' | 'Flat' | 'Co-living'
  amenities: string[]
  imageUrl: string
  description?: string
  bedrooms?: number
  bathrooms?: number
  sqft?: number
  deposit?: number
  hostName?: string
  hostImage?: string
  responseTime?: string
  viewsToday?: number
}

export const mockProperties: Property[] = [
  {
    id: 1,
    title: 'Royal Palms PG',
    location: 'Koramangala, Bangalore',
    city: 'Bangalore',
    price: 12500,
    currency: '₹',
    rating: 4.8,
    verified: true,
    type: 'PG',
    amenities: ['WIFI', 'AC', 'LAUNDRY'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANFX8kmGeAl-RIpe4lcNrcq8r0FJi1RQorOVQWXqs3IDaAEl-h51u07MdqNddTKC-wWWk0QYisJrSIZo37cdyTwRZ9rUHVL7Hnsx2Kr4urxv5LZmiY_mbZwj-3X8X4F21y2j_mlAkY5zChXSVGAQykvyRd-hPjJTEW1XF95CIDBaaT3xeuKqZE1sF0kUdFneeCv7sOli9YanyN2V4SuiWgf-3Vdk8PVW0oOsmpxTGaler3LYKtfwnojQ',
    description: 'A premium, modern co-living space designed for corporate professionals and students in Koramangala. Features spacious rooms, daily housekeeping, and premium food services.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 180,
    deposit: 25000,
    hostName: 'Kishore Kumar',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeWHCazXWOYOoMYevsUKkfGOMliJsKKCbw9oaA8Z-6ikZ6SNn0RQSYM5vm3cJA5aGv4-YFq6djpfoD9Juvx97OZ_aBBHzV2C7X3AhHYbcQrLYURjtslaSzu_J8tpRlabWJ-fvaUsoqF-DwLXKYjaCxptBbEQWdxPXrNg6LjWuaHkyPrhOMiyo5yLfXMInCb7pl-e4dztQttdirVEpIJD_aLzDHfPY9RF-A2dlmiHNK5xr9QwDh96lm-Q',
    responseTime: '< 30 mins',
    viewsToday: 24,
  },
  {
    id: 2,
    title: 'Zolo Skywalk',
    location: 'HSR Layout, Bangalore',
    city: 'Bangalore',
    price: 15000,
    currency: '₹',
    rating: 4.5,
    verified: true,
    type: 'Hostel',
    amenities: ['WIFI', 'GYM', 'CAFETERIA'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2MdsSwnT45-h0k4lAh9KbgchRaYGELyzVnLN_s194gy5RAjuFWgQpglbBxcGZup1z6ne6CnvMbCrcERVGoUEv9Z_SOJ-Hudcwb9fPqECJFXZRFFDZnsN0PvT_ykG2YT3uPQ_AZC1-FQpoz4ezywZ_nZin7VX5_2qrvOSC2z3DbCogfqiARCJoHa68-AF7cOyRRk8uqQPcoHnca8awUAtKeTIiA9b-hZQvDWQ8OvrWqCI8xVbji3xKmg',
    description: 'Nestled in the prime area of HSR Layout, Zolo Skywalk offers community living with dedicated workspace, standard amenities, and a high-end social rooftop area.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 200,
    deposit: 30000,
    hostName: 'Zolo Properties',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIYBJCx8AiWGjw0bEYgPeYQp8OIH_bRg60YOxZgRSxgvnAwGr54M9NzuAnPBgS0FXXURu90gdqVZlVulyxk-cPF83uaU2Y45GYgkD89yCDApkBBKCea0F4bNYH1YT0g8TpGnKWgSmkJk5PxEOueQc5lX6WYUekJWYN3EwDaWdVwe-ArO4jTV2V5ELel77Df-HtbzNG9CMJCR67VJ-_3FftfzH0vkFnmYeR5tNDrtkPohcARZjBppmQCQ',
    responseTime: '< 1 hour',
    viewsToday: 18,
  },
  {
    id: 3,
    title: 'The Hive Student Living',
    location: 'Bannerghatta, Bangalore',
    city: 'Bangalore',
    price: 18500,
    currency: '₹',
    rating: 4.9,
    verified: true,
    type: 'Hostel',
    amenities: ['FOOD', 'WIFI', 'BUS'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBpaM3vmTX1Q-jjEuoKpD_YCiEkedjGBuzYpCSoZCbEKYdxPvK1H6XfzP-MtJrZVzWNN-oEzU1BP1ZHkZbgup-oTAdvyLUru8hxkJf-JzEZkyebkzCryAKfMVnOapVLUxDXTpsPZWKDojeHz-0aE8V_Sqyyjy2-k_IRCdghaGV5SZmu9QrrlwaocYhUv1Q9I6R0YFR4ilirjgGKfYMKx-R0kaFj9Z1owEpAu6Y4mBIqt3V0lSnPUt44Rw',
    description: 'A modern, vibrant student hostel located directly opposite Bannerghatta Road college campuses. Offers twin sharing rooms, student transport, and library space.',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 320,
    deposit: 37000,
    hostName: 'The Hive Mgmt',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFgFdlFsqJ4obY9mfox_FbTNGVRQnJixzpZmgihUGycQMFRITtxTGBT1isT59DgNt-JZ5_k9cvEO7dDc7tFOTFkRgeLeRsin3AnK_m0-QW9Am3q-rgNrPwschr1drWxYE4dxeNDvdNtP1W9f7V4xm0HDOQbY2A5bR9hsx_dC7IdbssILwyYs7i2fHLL10WinI2CsXXDhQOHYUnaQaLc2rw-duFy8FIlRUBWUj0umP2U1ZK2Pe03wfDLA',
    responseTime: '< 15 mins',
    viewsToday: 42,
  },
  {
    id: 4,
    title: 'Mantri Elite 1BHK',
    location: 'Indiranagar, Bangalore',
    city: 'Bangalore',
    price: 28000,
    currency: '₹',
    rating: 4.7,
    verified: true,
    type: 'Flat',
    amenities: ['POOL', 'GYM', 'PARKING'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsvKDyI6BvdyCXh33NFYZwKOrVB7DY1djMrUarqgvpUQOnVTDydscq8Mxa-AUrRNW1jlrxbdWFFJskYZun4CoQTPZaoz5d2VkTPKBqWjaw8uX4Th_wpLyrJnDs_Ionjwoll2ltQIyvd8qwRwVRD4JH4Dxb-m0SYnS5zVc2y9hSEq22WYKSd53Bu4Y4saFodvmVkdiXQK6dbQhQexJ7SD68IeB7t68jS5GgkjNtA7C_okgdWSgaOhYmWg',
    description: 'An premium, upscale 1BHK flat in the heart of Indiranagar. The property comes with private resident pool access, secured parking space, and modern interiors.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    deposit: 80000,
    hostName: 'Mantri Owners',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0iNuVD1RK_hEbS6daLgkh-F_fzAq73C9RXwD4xgvpxeVe36vekIGNRDnP2iG_loKKHFOQqk1h0r5ZJScVao_DNoPexF_nsDVV4EhihDLd5vxDVQ41O4zRZUphrlxsOLDJqZHB-z3vj6_DL12YVZ2Skn83BnIvhRNz2Cl1T0uYC-tGndXnKzeF_gFGbNbtfBkOiSPIPSWXfc9s-Sgwm6i_rIy9JmCxXfLtzB91KkwsK0xC-Pky-yFMjg',
    responseTime: '< 2 hours',
    viewsToday: 15,
  },
  {
    id: 5,
    title: 'Lumina Student Studios',
    location: 'Bloomsbury, London',
    city: 'London',
    price: 1250,
    currency: '£',
    rating: 4.8,
    verified: true,
    type: 'Co-living',
    amenities: ['Free WiFi', 'En-suite'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUHkHeLYo5XnmRfDOoYO5hxtnNmLzUqyfReKlnmIcCpeEJ0lVrbFt9QzPZ_v8G4tO2ctQhbMtFdIZjzfOuuYFBHCmeMit8Q0O403w-QfT1biSH9S6MPiqQ6-ldnsCSEzDvXdOVBjUIDz1Y_2fSkfSodx1mwULKaAH5NTaJnkz9QgbOvW-frTI1XE3zt_fhbaOeQBFXvlu5gIoe3PS9gCIApnKpHRHLy0Ewyxb9uo-YPVXoSdAijO-lqw',
    description: 'A bright, modern sun-drenched studio apartment in London Bloomsbury, located just a short walk to UCL. Fully furnished, en-suite bathroom, and study-oriented environment.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 250,
    deposit: 1250,
    hostName: 'Lumina Housing',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAwaZwwrLvLJ28B6T4GYYe5oHGBJjsDJ_Y-Zt3uyMSyNJPhDfBDQX9ZjOY4bBl7NVHBCo6SZdPCwMn9l0xJ7B7RPfcWwYEY5I5DC-ZytaljnKLZ3XN6IcnZyeXoLn3rquPsEfr3AbW9LNa0Hub7OHBjvRDK5091o23q8r6SxhOv480Vjm0ZwSOWohOkF9Z7X-X71XVR75-GqvFCIFwbUvbFcNOOF-ORkXcjJIBT0JevQa-qTh-tIe8OFg',
    responseTime: '< 1 hour',
    viewsToday: 32,
  },
  {
    id: 6,
    title: 'Greenwich Shared Living',
    location: 'Greenwich, London',
    city: 'London',
    price: 850,
    currency: '£',
    rating: 4.5,
    verified: false,
    type: 'Co-living',
    amenities: ['Kitchen', 'Garden', 'Bills Incl.'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsSRnAaA8ean3WKhWRWpktgpm4HdbFa6-uDDgLsOY3KQgx3Et9_hNlEh9erfRfp4qD0Xv-VxkCEkyAHQ0eh1mZErZnk2Knk_eAsvRT3pOUGGo-Zft3a94DegD4c8Fq0IGHqB_0iH1tnVTEtX0HBwNXppUKLSrzzhNyXxLhgdpIa1L-DRElFRy-cAJTi3tkpuwGgUk7p3pUdS_aUoeFEJGH5k_emqKaIkZ0yLh0W9nq_jT5nHSmFtO2xw',
    description: 'A spacious shared townhouse in Greenwich. Rent includes all utility bills and high-speed broadband. Beautiful shared garden space and large common dining area.',
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1200,
    deposit: 850,
    hostName: 'Greenwich Homes',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeWHCazXWOYOoMYevsUKkfGOMliJsKKCbw9oaA8Z-6ikZ6SNn0RQSYM5vm3cJA5aGv4-YFq6djpfoD9Juvx97OZ_aBBHzV2C7X3AhHYbcQrLYURjtslaSzu_J8tpRlabWJ-fvaUsoqF-DwLXKYjaCxptBbEQWdxPXrNg6LjWuaHkyPrhOMiyo5yLfXMInCb7pl-e4dztQttdirVEpIJD_aLzDHfPY9RF-A2dlmiHNK5xr9QwDh96lm-Q',
    responseTime: '< 3 hours',
    viewsToday: 11,
  },
  {
    id: 7,
    title: 'Skyline Premium Dorms',
    location: 'Southbank, London',
    city: 'London',
    price: 1500,
    currency: '£',
    rating: 4.9,
    verified: true,
    type: 'Hostel',
    amenities: ['Gym', '24/7 Security', 'Concierge'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmSWY2PFWbGLseBA-kLJl2lm4_VFyeSCtyScA8QitzDcnvnKMdpIAZfOrqSImS_jg_pu7Uxiheg-0RDFEGbubs1_rYldwl0mSsVn5d3p3jnO0enKA8tDbKGLC0hMoKrhQW8FocKBauqvhQC8Tbr4BcgIbERochvCjEQPeXsgfb_PZ0t61xS2lg0nSQj4vMwpLxWokwAMd-pyPqmdcx8f-KZ1SaZKY5fsHZ-VXe5MkqgIDtojENZx-Yjw',
    description: 'Premium student dorms overlooking the Southbank and the London eye. Offers custom fitness suites, study pods, and standard high-security access controls.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 220,
    deposit: 1500,
    hostName: 'Skyline Living',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIYBJCx8AiWGjw0bEYgPeYQp8OIH_bRg60YOxZgRSxgvnAwGr54M9NzuAnPBgS0FXXURu90gdqVZlVulyxk-cPF83uaU2Y45GYgkD89yCDApkBBKCea0F4bNYH1YT0g8TpGnKWgSmkJk5PxEOueQc5lX6WYUekJWYN3EwDaWdVwe-ArO4jTV2V5ELel77Df-HtbzNG9CMJCR67VJ-_3FftfzH0vkFnmYeR5tNDrtkPohcARZjBppmQCQ',
    responseTime: '< 1 hour',
    viewsToday: 29,
  },
  {
    id: 8,
    title: 'The Artsy Attic',
    location: 'Camden Town, London',
    city: 'London',
    price: 980,
    currency: '£',
    rating: 4.2,
    verified: false,
    type: 'Flat',
    amenities: ['Pet Friendly', 'Balcony', 'Studio'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSR7fZAHroxl2lIJTPL2vh2e3RXqq97KpnqasDJtSieZab4yLfNW1FW9IsqOaP-57khhI-E7-IRgfTAypXu382bu1uAVm7ExzgAv65oqUA3Z1_S_f6RbZy48UvQISQ_lU02sYDI11Ts6qFJJFRRLcyT7FkoXuWlXXXQoEg7KLEX6-ECX22qn-o33gn0xHd-wkCpO3f9E4brZaIsbaFLkY8hxLnVfJG0PXbxXBM1R57OtE5CPz92_YpEw',
    description: 'A cozy, vibrant apartment with unique art-deco styling and a lovely sunset view balcony. Close to the Camden market and creative colleges.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 400,
    deposit: 1200,
    hostName: 'Artsy Estates',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFgFdlFsqJ4obY9mfox_FbTNGVRQnJixzpZmgihUGycQMFRITtxTGBT1isT59DgNt-JZ5_k9cvEO7dDc7tFOTFkRgeLeRsin3AnK_m0-QW9Am3q-rgNrPwschr1drWxYE4dxeNDvdNtP1W9f7V4xm0HDOQbY2A5bR9hsx_dC7IdbssILwyYs7i2fHLL10WinI2CsXXDhQOHYUnaQaLc2rw-duFy8FIlRUBWUj0umP2U1ZK2Pe03wfDLA',
    responseTime: '< 4 hours',
    viewsToday: 8,
  },
  {
    id: 9,
    title: 'Urban Zen Studio',
    location: 'Shoreditch, London',
    city: 'London',
    price: 1890,
    currency: '£',
    rating: 4.7,
    verified: true,
    type: 'Co-living',
    amenities: ['Workspace', 'AC', 'Elevator'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDy3GTJ8NI9xeo7hZ4RY1cIRCR0KZYsVCMkM7hTnla-C3XX-gg_RZ_IYYUEBGglWm1Zy1YovvrtQX-LysRy7_3k30qUEJBn179ggFA6s1AmxPtB-AmH5dz0GKrK02-KLADCcO-f1h-zx6VM4kPC7ZQR3ePKktrzIMkrZ-_tBMXaiWXr1G9ZI1rIQswN2cMs2Tb6mLSCn0hSiNLxRSZq83jsAVYa4vHm5kuOiTkWxn_v4tN5nV1Y13JkZQ',
    description: 'Premium Shoreditch studio custom designed for modern digital nomad productivity. Complete with super-fast fiber connections and private meeting spaces.',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 380,
    deposit: 2000,
    hostName: 'Zen Group Ltd',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0iNuVD1RK_hEbS6daLgkh-F_fzAq73C9RXwD4xgvpxeVe36vekIGNRDnP2iG_loKKHFOQqk1h0r5ZJScVao_DNoPexF_nsDVV4EhihDLd5vxDVQ41O4zRZUphrlxsOLDJqZHB-z3vj6_DL12YVZ2Skn83BnIvhRNz2Cl1T0uYC-tGndXnKzeF_gFGbNbtfBkOiSPIPSWXfc9s-Sgwm6i_rIy9JmCxXfLtzB91KkwsK0xC-Pky-yFMjg',
    responseTime: '< 30 mins',
    viewsToday: 35,
  },
  {
    id: 10,
    title: 'Greenwich Mews',
    location: 'Greenwich, London',
    city: 'London',
    price: 2100,
    currency: '£',
    rating: 5.0,
    verified: true,
    type: 'Flat',
    amenities: ['Garden', 'Pet Friendly', 'Laundry'],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuACXCeQoMD7ipQFUhZOMwfkFqs1WHA7vGAtxwYKu6ScUSsJ0GRsy4PKvkT2T4a-InO8iS4T3p0NB1OVxa6L87ifRfCgeI-kNcAwTglXIa9G7k7cRilkrt800BxKoaChTCDUdo7njX7rF-Me3SyAKnaVxx1DSpkNs0I8Ubg-rNmHcCTc1R6FOWNJYC6-seNnwgd3URSfB27N9smWnXYt0d-piar6z69xQVlahDtj39BtzqhWxdvgbXweKw',
    description: 'A beautiful mews house flat located inside historical Greenwich. Private garden area, modern luxury kitchen, and immediate access to Greenwich royal park.',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 850,
    deposit: 3000,
    hostName: 'Historic Rentals',
    hostImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIYBJCx8AiWGjw0bEYgPeYQp8OIH_bRg60YOxZgRSxgvnAwGr54M9NzuAnPBgS0FXXURu90gdqVZlVulyxk-cPF83uaU2Y45GYgkD89yCDApkBBKCea0F4bNYH1YT0g8TpGnKWgSmkJk5PxEOueQc5lX6WYUekJWYN3EwDaWdVwe-ArO4jTV2V5ELel77Df-HtbzNG9CMJCR67VJ-_3FftfzH0vkFnmYeR5tNDrtkPohcARZjBppmQCQ',
    responseTime: '< 1 hour',
    viewsToday: 14,
  },
]
